version: '3'
services:
  borgmatic:
    image: b3vis/borgmatic
    env_file: msmtp.env
    container_name: borgmatic
    volumes:
      - ${VOLUME_SOURCE}:/mnt/source:ro           # backup source
      - ${VOLUME_TARGET}:/mnt/borg-repository     # backup target
      - ${VOLUME_ETC_BORGMATIC}:/etc/borgmatic.d/ # borgmatic config file(s) + crontab.txt
      - ${VOLUME_DOT_BORGMATIC}:/root/.borgmatic  # borgmatic database dumps
      - ${VOLUME_BORG_CONFIG}:/root/.config/borg  # config and keyfiles
      - ${VOLUME_SSH}:/root/.ssh                  # ssh key for remote repositories
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg    # checksums used for deduplication
    environment:
      - TZ=${TZ}
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
