---
name: "build images"

on:
  push:
    branches:
      - master

env:
  image_name: ${{ IMAGE_NAMESPACE }}/borgmatic

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry: [quay.io]
        image_flavour: [base, msmtp, ntfy]
        arch: [amd64, arm64v8]
        include:
          - registry: quay.io
            username: ${{ QUAYIO_USERNAME }}
            password: ${{ QUAYIO_PASSWORD }}

          - image_flavour: base
            tag_name: latest
          - image_flavour: msmtp
            tag_name: latest-msmtp
          - image_flavour: ntfy
            tag_name: latest-ntfy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.registry }}
          username: ${{ matrix.username }}
          password: ${{ matrix.password }}

      - name: Build_base
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./${{ matrix.image_flavour }}
          file: ./${{ matrix.image_flavour }}/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ image_name }}:${{ matrix.tag_name }}
